#pragma config(Sensor, S1,     HTCS,                sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: HTCS-test2.c 49 2011-04-27 13:00:05Z xander $
 */

/**
 * HTCS-driver.h provides an API for the HiTechnic Color Sensor.  This program
 * demonstrates how to use that API.  This program allows you to calibrate the white
 * value for the Color Sensor.  Point the sensor at something you want the sensor to
 * detect as white and press the [enter] button.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 * - 0.3: Removed common.h from includes
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 2.00 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 20 February 2011
 * version 0.3
 */

#include "drivers/HTCS-driver.h"

task main () {
  // Get control over the buttons
  nNxtButtonTask  = -2;

  eraseDisplay();
  nxtDisplayTextLine(0, "HTCS Test 2");
  nxtDisplayTextLine(2, "Press orange");
  nxtDisplayTextLine(3, "button to start");
  nxtDisplayTextLine(4, "calibration.");
  nxtDisplayTextLine(5, "Press grey");
  nxtDisplayTextLine(6, "button to exit.");

  while(nNxtButtonPressed != kEnterButton);
  eraseDisplay();
  nxtDisplayTextLine(3, "Starting");
  nxtDisplayTextLine(4, "calibration.");

  // This call calibrates the white value.
  if (!HTCScalWhite(HTCS)) {
    eraseDisplay();
    PlaySound(soundException);
    nxtDisplayTextLine(3, "ERROR!!");
    nxtDisplayTextLine(5, "Calibration");
    nxtDisplayTextLine(6, "failed!!");
    wait1Msec(2000);
    StopAllTasks();
  }
  wait1Msec(1000);
}

/*
 * $Id: HTCS-test2.c 49 2011-04-27 13:00:05Z xander $
 */
