#pragma config(Sensor, S1,     HTMAG,               sensorAnalogInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: HTMAG-test1.c 48 2011-02-13 20:35:38Z xander $
 */

/**
 * HTMAG-driver.h provides an API for the HiTechnic Magnetic Field Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 2.00 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 27 July 2010
 * version 0.1
 */

#include "drivers/HTMAG-driver.h"

task main () {
  nxtDisplayCenteredTextLine(0, "HiTechnic");
  nxtDisplayCenteredBigTextLine(1, "MAGNETIC");
  nxtDisplayCenteredTextLine(3, "Field Sensor");
  nxtDisplayCenteredTextLine(4, "Test 1");
  nxtDisplayCenteredTextLine(5, "Connect Sensor");
  nxtDisplayCenteredTextLine(6, "to S1");

  wait1Msec(2000);

  nxtDisplayCenteredTextLine(5, "Press enter");
  nxtDisplayCenteredTextLine(6, "to set bias");

  wait1Msec(2000);
  eraseDisplay();
  while(true) {
    eraseDisplay();
    nxtDisplayTextLine(1, "Resetting");
    nxtDisplayTextLine(2, "bias");
    wait1Msec(500);

    // Start the calibration and display the offset
    nxtDisplayTextLine(2, "Bias: %4d", HTMAGstartCal(HTMAG));
    PlaySound(soundBlip);
    while(bSoundActive);
    while(nNxtButtonPressed != kNoButton) EndTimeSlice();

    while(nNxtButtonPressed != kEnterButton) {
      eraseDisplay();

      nxtDisplayTextLine(1, "Reading");
      // Read the current calibration offset and display it
      nxtDisplayTextLine(2, "Bias: %4d", HTMAGreadCal(HTMAG));

      nxtDisplayClearTextLine(4);
      // Read the current rotational speed and display it
      nxtDisplayTextLine(4, "Mag:   %4d", HTMAGreadVal(HTMAG));
      nxtDisplayTextLine(6, "Press enter");
      nxtDisplayTextLine(7, "to recalibrate");
      wait1Msec(100);
    }
  }
}

/*
 * $Id: HTMAG-test1.c 48 2011-02-13 20:35:38Z xander $
 */
